apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  name: gpu-admission
  namespace: kube-system
spec:
  containers:
  - image: gpu-admission-tke:36
    imagePullPolicy: Always
    name: gpu-admission
    env:
    - name: LOG_LEVEL
      value: "4"
    - name: EXTRA_FLAGS
      value: "--incluster-mode=false"
    ports:
    - containerPort: 3456
    volumeMounts:
    - mountPath: /etc/kubernetes/
      name: kubernetes
      readOnly: true
    - mountPath: /var/log/gpu-admission
      name: log
  dnsPolicy: ClusterFirstWithHostNet
  hostNetwork: true
  priority: 2000000000
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      type: Directory
      path: /etc/kubernetes/
    name: kubernetes
  - hostPath:
      type: DirectoryOrCreate
      path: /var/log/gpu-admission
    name: log
